/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      colors: {
        primary: {
          50: '#edfffe',
          100: '#d1fffd',
          200: '#a9fffb',
          300: '#6bfff8',
          400: '#00FFD1',
          500: '#00e0b8',
          600: '#00b899',
          700: '#009279',
          800: '#007361',
          900: '#005e51',
          950: '#003630',
        },
        neon: {
          cyan: '#00FFD1',
          blue: '#00d4ff',
          green: '#39FF14',
          pink: '#ff00ff',
        },
        surface: {
          DEFAULT: 'var(--color-surface)',
          dark: 'var(--color-surface-dark)',
          card: 'var(--color-surface-card)',
          hover: 'var(--color-surface-hover)',
          border: 'var(--color-border)',
        },
        txt: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          soft: 'var(--color-accent-soft)',
          border: 'var(--color-accent-border)',
          glow: 'var(--color-accent-glow)',
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'shimmer': 'shimmer 2s infinite',
        'like': 'like 0.6s ease-in-out',
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'float 8s ease-in-out infinite',
        'float-slower': 'float 10s ease-in-out infinite',
        'pulse-glow': 'pulseGlow 4s ease-in-out infinite',
        'slide-in-left': 'slideInLeft 0.6s ease-out',
        'slide-in-right': 'slideInRight 0.6s ease-out',
        'neon-pulse': 'neonPulse 2s ease-in-out infinite',
        'dot-grid-fade': 'dotGridFade 8s ease-in-out infinite alternate',
        'glow-line': 'glowLine 3s ease-in-out infinite',
        'border-glow': 'borderGlow 3s ease-in-out infinite alternate',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { transform: 'translateY(10px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        scaleIn: { '0%': { transform: 'scale(0.95)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        shimmer: { '0%': { backgroundPosition: '-1000px 0' }, '100%': { backgroundPosition: '1000px 0' } },
        like: { '0%, 100%': { transform: 'scale(1)' }, '15%': { transform: 'scale(1.2)' }, '30%': { transform: 'scale(0.95)' }, '45%, 80%': { transform: 'scale(1)' } },
        float: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-20px)' } },
        pulseGlow: { '0%, 100%': { opacity: '0.4', transform: 'scale(1)' }, '50%': { opacity: '0.8', transform: 'scale(1.05)' } },
        slideInLeft: { '0%': { opacity: '0', transform: 'translateX(-30px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        slideInRight: { '0%': { opacity: '0', transform: 'translateX(30px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        neonPulse: {
          '0%, 100%': { boxShadow: '0 0 5px rgba(0, 255, 209, 0.3), 0 0 10px rgba(0, 255, 209, 0.1)' },
          '50%': { boxShadow: '0 0 15px rgba(0, 255, 209, 0.5), 0 0 30px rgba(0, 255, 209, 0.2)' },
        },
        dotGridFade: { '0%': { opacity: '0.3' }, '100%': { opacity: '0.6' } },
        glowLine: { '0%, 100%': { opacity: '0.3', transform: 'scaleX(0.8)' }, '50%': { opacity: '0.7', transform: 'scaleX(1)' } },
        borderGlow: { '0%': { borderColor: 'rgba(0, 255, 209, 0.08)' }, '100%': { borderColor: 'rgba(0, 255, 209, 0.2)' } },
      },
      backgroundImage: {
        'dot-grid': 'radial-gradient(circle, rgba(255,255,255,0.06) 1px, transparent 1px)',
        'neon-gradient': 'linear-gradient(135deg, #00FFD1 0%, #00d4ff 100%)',
        'neon-gradient-soft': 'linear-gradient(135deg, rgba(0,255,209,0.15) 0%, rgba(0,212,255,0.08) 100%)',
      },
      backgroundSize: {
        'dot-grid': '24px 24px',
      },
      boxShadow: {
        'neon': 'var(--shadow-neon)',
        'neon-sm': 'var(--shadow-neon-sm)',
        'neon-lg': 'var(--shadow-neon)',
        'card-glow': 'var(--shadow-card)',
      },
    },
  },
  plugins: [],
}
